project_id = "zlrgwfvqhxpfnuvxpyce"

[functions.spotify-auth]
verify_jwt = false

[functions.spotify-playlists]
verify_jwt = true

[functions.spotify-play]
verify_jwt = true

[functions.ping]
verify_jwt = false
